### ISSUE TITLE
Possível bug - NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by emersonoliveiradev** [pagarme/pagarme-python#121]
Durante a execução do  **pagarme.transaction.create(data)** é retornado no terminal algo como:

Traceback (most recent call last):
  File "pg.py", line 81, in <module>
    trx = pagarme.transaction.create(data)
  File "/home/haw/.local/lib/python3.7/site-packages/pagarme/transaction.py", line 14, in create
    return handler_request.post(transaction_routes.BASE_URL, dictionary)
  File "/home/haw/.local/lib/python3.7/site-packages/pagarme/resources/handler_request.py", line 46, in post
    pagarme_response = requests_retry_session().post(end_point, json=data)
  File "/home/haw/.local/lib/python3.7/site-packages/pagarme/resources/requests_retry.py", line 21, in requests_retry_session
    session.headers.update(headers())
  File "/home/haw/.local/lib/python3.7/site-packages/pagarme/resources/requests_retry.py", line 9, in headers
    'User-Agent': 'pagarme-python/{} python/{}'.format(sdk.VERSION, sys.version.split(' ',1)[0]),
NameError: name 'sys' is not defined

Resolvi localmente em meu ambiente virtual apenas adicionando: **import sys** em:
~/.virtualenvs/brioche_food/lib/python3.7/site-packages/pagarme/resources/requests_retry.py

**Comment by jonatasmaxi** [comment]
Opa @emersonoliveiradev obrigado pelo report, vamos ver de incluir a importação diretamente no arquivo de requests
